### ISSUE TITLE
Not Syncing SMS - String Error

### ISSUE THREAD

**Issue by dnsinformatic** [nextcloud/ocsms#180]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Should Sync SMS from Android 6.0

### Actual behaviour
@ Phone getting error 9

On Server getting string error
Does nos sync any sms from phone to nextcloud

### Server configuration

**NextCloud/ownCloud version:**
Nextcloud 11.0.3
**PHP version:**
7.0
**HTTPd server:**

**HTTPS:**
https://dnscloud.dtdns.net
### Client configuration

**Android version:**
6.0

**Phone:**
Huawei P8 lite
**ownCloud SMS app version:**
Nextcloud SMS version 1.0.0
### Logs

```
{"reqId":"DMZVqWFA7vgflnaW5SfO","remoteAddr":"89.109.115.82","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'INSERT INTO oc_ocsms_smsdatas (user_id, added, lastmodified, sms_flags, sms_date, sms_id,sms_address, sms_msg, sms_mailbox, sms_type) VALUES (?,?,?,?,?,?,?,?,?,?)' with params [\\\"DNS\\\", \\\"2017-04-28 13:43:52\\\", \\\"2017-04-28 13:43:52\\\", \\\"11\\\", \\\"1492182214056\\\", 125, \\\"+351965197113\\\", \\\"Tamos saindo. Get ready \\\\ud83d\\\\ude0d\\\", 0, 1]:\\n\\nSQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\\\xF0\\\\x9F\\\\x98\\\\x8D' for column 'sms_msg' at row 1\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/DNSCloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/DNSCloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(177): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO oc_...', Array)\\n#2 \\\/var\\\/www\\\/DNSCloud\\\/lib\\\/private\\\/legacy\\\/db\\\/statementwrapper.php(74): Doctrine\\\\DBAL\\\\Statement->execute(Array)\\n#3 \\\/var\\\/www\\\/DNSCloud\\\/apps\\\/ocsms\\\/db\\\/smsmapper.php(289): OC_DB_StatementWrapper->execute(Array)\\n#4 \\\/var\\\/www\\\/DNSCloud\\\/apps\\\/ocsms\\\/controller\\\/apicontroller.php(82): OCA\\\\OcSms\\\\Db\\\\SmsMapper->writeToDB('DNS', Array)\\n#5 [internal function]: OCA\\\\OcSms\\\\Controller\\\\ApiController->push(16, Array)\\n#6 \\\/var\\\/www\\\/DNSCloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/DNSCloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\OcSms\\\\Controller\\\\ApiController), 'push')\\n#8 \\\/var\\\/www\\\/DNSCloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\OcSms\\\\Controller\\\\ApiController), 'push')\\n#9 \\\/var\\\/www\\\/DNSCloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ApiController', 'push', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/var\\\/www\\\/DNSCloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#12 \\\/var\\\/www\\\/DNSCloud\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/apps\\\/ocsms\\\/pus...')\\n#13 \\\/var\\\/www\\\/DNSCloud\\\/index.php(40): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/DNSCloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":116}","level":3,"time":"2017-04-28T13:43:52+00:00","method":"POST","url":"\/index.php\/apps\/ocsms\/push?format=json","user":"DNS","version":"11.0.3.2"}

```

**Comment by nerzhul** [comment]
Hello,
please read this link for MySQL: https://github.com/nextcloud/ocsms#question-solve-encoding-errors-on-mysql
Thanks
